%YAML:1.0
line segments: !!opencv-matrix
   rows: 35
   cols: 4
   dt: d
   data: [ -8.0, -8.0,  8.0, -8.0, 
            8.0, -8.0,  8.0,  8.0,
            8.0,  8.0, -8.0,  8.0,
           -8.0,  8.0, -8.0, -8.0,
           
           -5.6, -3.4, -3.9, -3.4,
           -3.9, -3.4, -3.9, -0.8,
           -3.9, -0.8, -5.6, -0.9,
           -5.6, -0.9, -5.6, -3.4, 
           
           -4.8,  2.2, -3.0,  2.3,
           -3.0,  2.3, -3.0,  4.5,
           -3.0,  4.5, -4.9,  4.4,
           -4.9,  4.4, -4.8,  2.2,
           
            4.5, -8.0,  4.4, -5.2,
            4.4, -5.2,  8.0, -5.2,
            
           -1.1, -4.4,  2.5, -4.1,
            2.5, -4.1,  2.5, -2.3,
            2.5, -2.3, -1.1, -2.5,
           -1.1, -2.5, -1.1, -4.4,
           
           -1.1,  3.9,  1.4,  3.9,
            1.4,  3.9,  1.3,  6.3,
            1.3,  6.3, -1.1,  6.3,
           -1.1,  6.3, -1.1,  3.9,
           
           -5.6,  6.4, -3.7,  6.4,
           
            8.0, -1.0,  3.6, -0.5,
            3.6, -0.5,  3.0, -1.1,
            3.0, -1.1,  1.7, -0.3,
            1.7, -0.3, -1.0, -0.2,
           -1.0, -0.2, -0.9,  1.6,
           -0.9,  1.6,  0.1,  1.6,
            0.1,  1.6,  0.3,  1.8,
            0.3,  1.8,  2.9,  1.7,
            2.9,  1.7,  3.9,  3.3,
            3.9,  3.3,  5.6,  2.3,
            5.6,  2.3,  5.0,  1.6,
            5.0,  1.6,  8.0,  1.4]
