%YAML:1.0
line segments: !!opencv-matrix
   rows: 9
   cols: 4
   dt: d
   data: [ -8.0, -8.0,  8.0, -8.0, 
            8.0, -8.0,  8.0,  8.0,
            8.0,  8.0, -8.0,  8.0,
           -8.0,  8.0, -8.0, -8.0,
           
           -5.3,  4.1,  4.4,  1.6,
            4.4,  1.6,  3.1, -3.3,
            3.1, -3.3,  0.7,  0.7,
            0.7,  0.7, -1.9,  0.1,
           -1.9,  0.1, -5.3,  4.1]
